service: nvdb2osm-pipeline
frameworkVersion: '2'

package:
  patterns:
    - '!workdir/**'
    - '!python-env/**'

provider:
  name: aws
  region: eu-north-1
  runtime: nodejs14.x
  iamManagedPolicies:
    - !Ref Nvdb2OsmPipelineLaunchEc2InstancesPolicy

functions:
  startNvdb2OsmEC2:
    handler: lambda/start-nvdb2osm-ec2.handler
    logRetentionInDays: 7
    timeout: 120 # 2 minutes
    memorySize: 128
    events:
      # run each 21st of a month (as it seems that most files are being updated on the 20st of each month)
      - schedule: cron(0 8 21 * ? *)

plugins:
  - serverless-plugin-log-retention

custom:
  logRetentionInDays: 7 # global retention for logs

resources:
  Resources:
    Nvdb2OsmPipelineLaunchEc2InstancesPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: Nvdb2OsmPipelineLaunchEc2InstancesPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:*
                - iam:PassRole
              Resource:
                - '*'
