service: nvdb2osm-pipeline
frameworkVersion: '3'

package:
  patterns:
    - '!workdir/**'
    - '!python-env/**'

provider:
  name: aws
  region: eu-north-1
  runtime: nodejs20.x
  iamManagedPolicies:
    - !Ref LaunchEc2InstancesPolicy
    - !Ref DataBucketAccessManagedPolicy

functions:
  startNvdb2OsmEC2:
    handler: lambda/start-nvdb2osm-ec2.handler
    logRetentionInDays: 7
    timeout: 120 # 2 minutes
    memorySize: 128
    events:
      - schedule: cron(0 5 15 * ? *) # needs to be in sync with the S3 remove rule below
    environment:
      INSTANCE_PROFILE_ARN: !GetAtt Ec2InstanceProfileForDataConversion.Arn
      UPLOAD_BUCKET_NAME: !Ref UploadBucket
      LASTKAJEN_USER: ${ssm:/nvdb2osm/lastkajen/user}
      LASTKAJEN_PASS: ${ssm:/nvdb2osm/lastkajen/pass}

  generateIndexHtml:
    handler: lambda/generate-index-html.handler
    logRetentionInDays: 7
    events:
      - schedule: rate(6 hours)
    environment:
      UPLOAD_BUCKET_NAME: !Ref UploadBucket

plugins:
  - serverless-plugin-log-retention

custom:
  logRetentionInDays: 7 # global retention for logs
  dataBucketName: nvdb-osm-map-data

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.dataBucketName}
        WebsiteConfiguration:
          ErrorDocument: 404.html
          IndexDocument: index.html
        LifecycleConfiguration:
          Rules:
            - Id: RemoveOldFiles
              Status: Enabled
              ExpirationInDays: 90 #needs to be synched with the EC2 lambda above
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false            

    DataBucketAccessManagedPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: NvdbDataBucketAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:ListBucket
                - s3:PutObjectAcl
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::${self:custom.dataBucketName}/*
                - arn:aws:s3:::${self:custom.dataBucketName}

    LaunchEc2InstancesPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: LaunchEc2InstancesPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:*
                - iam:PassRole
              Resource:
                - '*'

    Ec2RoleForDataConversion:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Ec2RoleForDataConversion
        Description: Role to let the EC2 instance that runs nvdb2osm.py access the data bucket
        ManagedPolicyArns:
          - !Ref DataBucketAccessManagedPolicy
          - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'

    Ec2InstanceProfileForDataConversion:
      Type: AWS::IAM::InstanceProfile
      Properties:
        InstanceProfileName: Ec2InstanceProfileForDataConversion
        Roles:
          - !Ref Ec2RoleForDataConversion
